[tool.mypy]
warn_unused_configs = true
ignore_missing_imports = false
disallow_untyped_defs = true
disallow_incomplete_defs = true
no_implicit_optional = true
strict_equality = true
warn_unreachable = true
warn_unused_ignores = true
show_error_context = true
pretty = true
check_untyped_defs = true
python_version = "3.12"
files = [
    "tasktiger"
]

[[tool.mypy.overrides]]
module = ["flask_script.*", "rollbar.*", "structlog.*"]
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]